services:
  postgres:
    image: postgres:16  # or use one online service like https://console.neon.tech
    container_name: finance-ai-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME:-finance_ai}
      POSTGRES_PASSWORD: ${DB_PASWORD:-passwd!}
      POSTGRES_DB: ${DB_DATABASE:-finance_ai}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - finance-ai-postgres:/var/lib/postgresql/data

volumes:
  finance-ai-postgres:
    driver: local

    